INSERT INTO components (name, type_id, description, price) VALUES
('Thin Crust', 1, 'A crispy, crunchy base that is thinner than traditional crusts, popular for a lighter, crispier texture.', 5.99),
('Thick Crust', 1, 'A more substantial, doughy crust that provides a soft and chewy bite, often found in deep-dish or pan pizzas.', 6.99),
('Neapolitan Crust', 1, 'Traditional Italian pizza crust, very thin and soft in the center with a slightly crispy outer edge, typically cooked in a wood-fired oven.', 7.49),
('Stuffed Crust', 1, 'A crust filled with cheese (or other fillings) around the edges, creating a gooey, cheesy outer ring.', 8.99),
('Deep Dish Crust', 1, 'A thick, buttery crust that is baked in a deep pan, creating a pie-like pizza with a substantial base, often associated with Chicago-style pizza.', 9.49),
('Gluten-Free Crust', 1, 'Made without wheat flour, often using rice flour, almond flour, or a mix of gluten-free ingredients, ideal for those with gluten intolerance.', 7.99),
('Whole Wheat Crust', 1, 'Made with whole wheat flour, giving the crust a denser texture and a slightly nutty flavor, considered a healthier alternative.', 6.49),
('Cauliflower Crust', 1, 'A low-carb, gluten-free alternative made primarily from cauliflower, often used for those looking for a lighter option.', 7.99),
('Cheese-Stuffed Crust', 1, 'A variation of the stuffed crust where cheese is melted inside the outer edges of the crust, creating a cheesy, indulgent layer.', 9.99),
('Sicilian Crust', 1, 'A thick, square-shaped crust with a soft and airy texture, typically topped with hearty ingredients and often associated with Sicilian pizza.', 8.49),
('Flatbread Crust', 1, 'A thin, flat base that is often slightly crispy, commonly used for gourmet or artisan pizzas.', 6.79),
('Pan Crust', 1, 'A thick, soft, and airy crust baked in a deep pan, creating a crisp bottom with a chewy interior, often associated with chain pizza places.', 7.49),
('Tomato Sauce', 2, 'A classic pizza sauce made from tomatoes, often seasoned with garlic, herbs, and spices for a savory base.', 2.99),
('Pesto Sauce', 2, 'A flavorful sauce made from basil, garlic, pine nuts, parmesan, and olive oil, offering a fresh and herby flavor.', 3.49),
('White Sauce', 2, 'A creamy sauce made from a base of butter, cream, and garlic, typically used for white pizzas or as a base for gourmet toppings.', 3.99),
('Barbecue Sauce', 2, 'A sweet and smoky sauce made from tomatoes, vinegar, and spices, commonly used for BBQ chicken or pork pizzas.', 3.49),
('Buffalo Sauce', 2, 'A tangy and spicy sauce made from hot sauce, butter, and vinegar, perfect for pizzas with a kick of heat.', 3.29),
('Garlic Sauce', 2, 'A rich sauce made from garlic, butter, and herbs, offering a savory, garlicky flavor ideal for various types of pizza.', 2.79),
('Alfredo Sauce', 2, 'A rich, creamy sauce made from butter, cream, and parmesan cheese, often used for white, chicken, or seafood pizzas.', 4.49),
('Ranch Sauce', 2, 'A creamy, tangy sauce made from buttermilk, herbs, and spices, often used as a dip or on pizzas for a mild, cool flavor.', 3.29),
('Marinara Sauce', 2, 'A simple, flavorful tomato-based sauce made with garlic, onions, and herbs, often used for classic pizzas and pasta dishes.', 2.49),
('Sriracha Sauce', 2, 'A spicy, tangy sauce made from chili peppers, vinegar, and garlic, adding a zesty heat to any pizza.', 3.19),
('Teriyaki Sauce', 2, 'A sweet and savory sauce made from soy sauce, ginger, garlic, and sugar, adding an Asian flair to pizzas, especially with chicken or beef.', 3.79),
('Curry Sauce', 2, 'A fragrant, spiced sauce made from curry spices, tomatoes, and cream, offering a unique flavor profile for gourmet pizzas.', 3.99),
('Mozzarella', 3, 'A soft, mild, and stretchy cheese that melts beautifully, commonly used as the base cheese for pizzas.', 4.49),
('Parmesan', 3, 'A hard, sharp cheese with a nutty flavor, often grated and sprinkled over pizzas for an extra layer of flavor.', 3.99),
('Cheddar', 3, 'A firm, slightly tangy cheese that adds a rich, sharp flavor, often used for more flavorful, indulgent pizzas.', 4.29),
('Gorgonzola', 3, 'A blue cheese with a strong, tangy flavor, perfect for gourmet pizzas, especially those with pears or walnuts.', 5.49),
('Provolone', 3, 'A semi-soft, mild cheese with a slightly smoky flavor, commonly used in combination with mozzarella on pizzas.', 4.99),
('Goat Cheese', 3, 'A soft cheese with a tangy, creamy texture, often used on gourmet pizzas with vegetables or fresh herbs.', 5.99),
('Ricotta', 3, 'A soft, creamy cheese with a mild flavor, typically used as a dollop on white pizzas or in combination with other cheeses.', 4.79),
('Feta', 3, 'A crumbly, salty cheese made from sheep’s milk, often used on Mediterranean-style pizzas with ingredients like olives or spinach.', 5.19),
('Gruyère', 3, 'A firm, nutty Swiss cheese that adds a rich, complex flavor to pizzas, often used in combination with other cheeses.', 5.59),
('Fontina', 3, 'A semi-soft, creamy cheese with a mild to slightly tangy flavor, great for melting and pairing with a variety of toppings.', 5.29),
('Burrata', 3, 'A fresh, creamy cheese with a soft outer shell and a rich, milky interior, often used on pizzas for an indulgent touch.', 6.49),
('Mascarpone', 3, 'A creamy, rich cheese with a sweet flavor, often used in white pizzas or as a base for dessert-style pizzas.', 6.99),
('Pepperoni', 4, 'A spicy, cured meat made from pork and beef, sliced thin and crisped up during baking, a classic pizza topping.', 2.99),
('Mushrooms', 4, 'Fresh, earthy mushrooms that add a savory flavor and meaty texture, perfect for vegetarian or meat lover pizzas.', 1.79),
('Sausage', 4, 'Ground pork or beef sausage, seasoned with herbs and spices, often crumbled on top of pizzas for a savory, hearty topping.', 2.49),
('Olives', 4, 'Black or green olives, adding a briny, tangy flavor that complements Mediterranean-style pizzas or vegetable toppings.', 1.99),
('Onions', 4, 'Fresh, sliced onions, offering a mild, slightly sweet flavor when cooked, a versatile topping for many pizza styles.', 1.49),
('Bell Peppers', 4, 'Colorful and sweet bell peppers, adding crunch and freshness to pizzas, often paired with onions and mushrooms.', 1.99),
('Bacon', 4, 'Crispy, crumbled bacon, adding a smoky, salty crunch to pizzas, often paired with vegetables or used on meat lover’s pizzas.', 2.99),
('Ham', 4, 'Tender, thinly sliced ham, often used on Hawaiian-style pizzas or as a topping for more traditional pies.', 2.49),
('Anchovies', 4, 'Salted and preserved fish, providing a bold, salty flavor, often used on gourmet or classic Mediterranean pizzas.', 2.29),
('Pineapple', 4, 'Sweet, juicy pineapple chunks, often paired with ham for the controversial but beloved Hawaiian pizza.', 1.99),
('Fresh Basil', 4, 'Fresh basil leaves, adding a fragrant, herbal note that complements tomato-based sauces and mozzarella.', 1.79),
('Chicken', 4, 'Grilled or roasted chicken, often used on BBQ or gourmet-style pizzas, adding a mild, lean protein topping.', 2.99),
('Spinach', 4, 'Fresh spinach, often used on white pizzas or paired with cheese and garlic for a light, healthy topping.', 1.79),
('Tomatoes', 4, 'Fresh, sliced tomatoes, offering a juicy, sweet flavor, often used on Margherita pizzas or with Mediterranean toppings.', 1.59),
('Jalapeños', 4, 'Spicy, sliced jalapeño peppers, adding heat and zest to pizzas, especially for those who love a spicy kick.', 1.89),
('Oregano', 5, 'A fragrant herb with a slightly bitter, peppery flavor, commonly sprinkled on top of pizzas for added aroma and taste.', 0.99),
('Basil', 5, 'A fresh, sweet herb with a mild, peppery flavor, often used on Italian-style pizzas, especially Margherita.', 1.29),
('Garlic Powder', 5, 'A ground, dehydrated form of garlic, adding a savory, pungent flavor to pizza sauces, crusts, or toppings.', 0.79),
('Chili Flakes', 5, 'Crushed red chili peppers that add a spicy kick, commonly sprinkled on pizzas for those who like heat and heat-related flavor.', 0.89),
('Parmesan Cheese', 5, 'Grated parmesan cheese that adds a sharp, salty, and nutty flavor, often sprinkled on pizzas after baking for extra taste.', 1.49),
('Italian Seasoning', 5, 'A blend of dried herbs, including basil, oregano, thyme, and rosemary, commonly used for pizza sauces and toppings.', 1.19),
('Rosemary', 5, 'A fragrant herb with a pine-like flavor, often used to season the crust or topping of gourmet pizzas.', 1.39),
('Garlic Salt', 5, 'A mixture of garlic and salt, used to season the crust or toppings of pizzas for a more intense garlic flavor.', 0.89),
('Cajun Seasoning', 5, 'A bold blend of spices, including paprika, cayenne, and garlic, offering a spicy and smoky kick for meat lover pizzas or those seeking heat.', 1.29),
('Fennel Seeds', 5, 'A sweet, slightly licorice-flavored seed, often used in sausage or pizza dough for a unique aromatic touch.', 1.09),
('Cumin', 5, 'A warm, earthy spice, often used in fusion or gourmet pizzas, adding depth and a slightly smoky flavor.', 1.19),
('Lemon Zest', 5, 'Grated lemon peel, providing a bright, citrusy flavor that pairs well with white pizzas, seafood, or herb-based pizzas.', 1.49);